#!/bin/bash

# Initialize grades array.
declare -A grades
for group in "311CC" "312CC" "313CC" "314CC" "315CC"; do
    grades["$group"]=2
done

# Print groups and grades.
for group in "311CC" "312CC" "313CC" "314CC" "315CC"; do
    echo "$group,${grades[$group]}"
done
