all: main

main: main.o sum/sum.o sum/add/add.o utils/utils.o
	gcc -Wall main.o sum/sum.o sum/add/add.o utils/util.so -o main

main.o:
	#TODO

sum/sum.o:
	#TODO

sum/add/add.o:
	#TODO

utils/utils.o:
	#TODO

clean:
	rm -f main main.o sum/sum.o sum/add/add.o utils/utils.o
